import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowRight, ArrowUpRight, Gift, Heart, PackageCheck, Truck } from 'lucide-react';
import { serverApi } from '@/lib/api';
import type { ProductList } from '@/lib/types';
import { ProductCard } from '@/components/product-card';
export default async function Home() {
  let catalog: ProductList | null = null;
  try { catalog = await serverApi<ProductList>('/products?featured=true&limit=4'); } catch { /* Render a recoverable catalog state while the API starts. */ }
  const categories = [{ name: 'Ropa', note: 'Tu esencia, en cada prenda', slug: 'ropa', image: 'dress' }, { name: 'Zapatos', note: 'Pasos que dejan huella', slug: 'zapatos', image: 'heels' }, { name: 'Bolsos', note: 'Lleva contigo lo especial', slug: 'bolsos', image: 'bag' }, { name: 'Joyería', note: 'Pequeños grandes detalles', slug: 'joyeria', image: 'jewelry' }, { name: 'Accesorios', note: 'El toque que lo cambia todo', slug: 'accesorios', image: 'sunglasses' }];
  return <><section className="hero"><div className="hero-copy"><div className="hero-collection"><span /> NUEVA COLECCIÓN · ESENCIA</div><h1>El lujo de<br />sentirte <em>tú.</em></h1><p>Piezas que no solo vistes.<br />Piezas que hablan de ti.</p><Link className="button" href="/catalogo">Descubre la colección <ArrowUpRight size={18} /></Link><div className="hero-caption"><span className="tiny-star">✧</span> Elegidas con intención. Creadas para acompañarte.</div><a href="#universo" className="hero-scroll"><span>EXPLORA TU UNIVERSO</span><ArrowDown size={15} /></a></div><div className="hero-visual"><Image src="/images/editorial-hero.webp" alt="Colección Esencia: vestido marfil y bolso caramelo en un patio bañado por el sol" fill priority sizes="(max-width: 760px) 100vw, 58vw" /><div className="hero-vertical">LUXE WOMAN — COLECCIÓN ESENCIA</div><Link href="/catalogo?categoria=ropa" className="hero-glass"><span><small>MENOS RUIDO. MÁS ESENCIA.</small>La belleza de lo simple</span><span className="round-arrow"><ArrowUpRight size={23} /></span></Link><div className="hero-image-number">01 <span>/ 03</span></div></div></section>
  <div className="benefit-strip"><span><Truck size={19} strokeWidth={1.25} />Envíos a toda Colombia</span><i /><span><PackageCheck size={19} strokeWidth={1.25} />Detalles que marcan la diferencia</span><i /><span><Gift size={19} strokeWidth={1.25} />Una experiencia especial</span><i /><span><Heart size={19} strokeWidth={1.25} />Elegido con amor para ti</span></div>
  <section id="universo" className="section category-section"><div className="section-heading"><div><span className="eyebrow">TU ESTILO, SIN LÍMITES</span><h2>Un universo por descubrir</h2></div><p>Cada detalle cuenta.<br />Encuentra lo que te hace única.</p></div><div className="category-grid">{categories.map((category, i) => <Link className="category-card" href={`/catalogo?categoria=${category.slug}`} key={category.slug}><div className="category-image"><Image src={`/images/${category.image}.jpg`} alt={`Selección de ${category.name.toLowerCase()}`} fill sizes="(max-width: 600px) 44vw, 18vw" /><span className="category-number">0{i + 1}</span></div><div className="category-label"><span><h3>{category.name}</h3><small>{category.note}</small></span><ArrowUpRight size={21} strokeWidth={1.2} /></div></Link>)}</div></section>
  <section className="section favorites-section"><div className="section-heading"><div><span className="eyebrow">AMOR A PRIMERA VISTA</span><h2>Tus próximos imprescindibles</h2></div><Link className="text-link" href="/catalogo">Ver toda la colección <ArrowRight size={17} /></Link></div>{catalog ? <div className="product-grid">{catalog.items.map(product => <ProductCard key={product.id} product={product} />)}</div> : <div className="empty-state"><h3>Estamos preparando nuestra selección</h3><p>El catálogo estará disponible al conectar la boutique.</p><Link href="/catalogo" className="text-link">Volver a consultar <ArrowRight size={16} /></Link></div>}</section>
  <section className="editorial"><div className="editorial-image"><Image src="/images/editorial-hero.webp" alt="Los tonos cálidos y las texturas naturales de la colección Esencia" fill sizes="(max-width: 760px) 100vw, 50vw" /></div><div className="editorial-copy"><span className="eyebrow">EL UNIVERSO LUXE WOMAN</span><span className="editorial-star">✧</span><h2>No es solo lo que llevas.<br />Es cómo te <em>sientes.</em></h2><p>Creemos en la elegancia que nace de ser tú misma. En los detalles que enamoran y en esas piezas que se convierten en parte de tu historia.</p><Link href="/nosotros" className="text-link">Conoce nuestra esencia <ArrowRight size={17} /></Link></div></section>
  <section className="club section"><span className="eyebrow">UN ESPACIO PARA TI</span><h2>Lo especial se comparte.</h2><p>Guarda tus favoritos, descubre nuevas piezas<br />y vive el universo LUXE a tu manera.</p><Link href="/cuenta?modo=registro" className="button button-secondary">Sé parte de LUXE WOMAN <ArrowRight size={17} /></Link><small>Tu estilo. Tus favoritos. Tu pequeño universo.</small></section></>;
}
