import '../src/config';
import { Database } from '../src/database';
import { defaultSettings } from '../src/domain';
import { hash } from 'bcryptjs';
const db=new Database();
async function main(){
  if(process.env.NODE_ENV==='production')throw new Error('El seed de demostración está deshabilitado en producción.');
  const categories=[{id:'cat-ropa',slug:'ropa',name:'Ropa',image:'/images/dress.jpg'},{id:'cat-zapatos',slug:'zapatos',name:'Zapatos',image:'/images/heels.jpg'},{id:'cat-joyeria',slug:'joyeria',name:'Joyería',image:'/images/jewelry.jpg'},{id:'cat-bolsos',slug:'bolsos',name:'Bolsos',image:'/images/bag.jpg'},{id:'cat-accesorios',slug:'accesorios',name:'Accesorios',image:'/images/sunglasses.jpg'}];
  for(const category of categories)await db.category.upsert({where:{slug:category.slug},create:category,update:{}});
  const products=[
    {slug:'vestido-alma',name:'Vestido Alma',categoryId:'cat-ropa',price:249900,compareAtPrice:299900,image:'/images/dress.jpg',color:'Marfil',hex:'#F3ECE2',sizes:['XS','S','M','L'],description:'Una silueta que se mueve contigo. Vestido midi de caída suave y líneas limpias, pensado para los momentos que merecen sentirse especiales.',materials:'Mezcla de viscosa y lino.',details:'Corte midi, escote delicado y ajuste fluido.',care:'Lavar a mano con agua fría. Secar a la sombra.',featured:true,isNew:true},
    {slug:'bolso-siena',name:'Bolso Siena',categoryId:'cat-bolsos',price:189900,compareAtPrice:null,image:'/images/bag.jpg',color:'Caramelo',hex:'#B78966',sizes:['Única'],description:'El equilibrio entre lo esencial y lo extraordinario. Un bolso estructurado con espacio para acompañarte durante todo el día.',materials:'Material sintético de acabado suave. Forro textil.',details:'Correa ajustable, cierre seguro y bolsillo interior.',care:'Limpiar con un paño suave ligeramente húmedo.',featured:true,isNew:false},
    {slug:'sandalia-aura',name:'Sandalia Aura',categoryId:'cat-zapatos',price:179900,compareAtPrice:219900,image:'/images/heels.jpg',color:'Nude',hex:'#C7A28C',sizes:['35','36','37','38','39','40'],description:'La elegancia está en los pequeños pasos. Sandalias de líneas delicadas y tacón cómodo para elevar cada uno de tus looks.',materials:'Exterior sintético y suela de goma.',details:'Tacón de 6 cm y tira ajustable al tobillo.',care:'Evitar humedad prolongada. Limpiar con paño seco.',featured:true,isNew:true},
    {slug:'collar-eclat',name:'Collar Éclat',categoryId:'cat-joyeria',price:89900,compareAtPrice:null,image:'/images/jewelry.jpg',color:'Dorado',hex:'#C5A16B',sizes:['Única'],description:'Un destello sutil que ilumina lo cotidiano. Una pieza delicada para llevar sola o crear tu propia combinación.',materials:'Acero inoxidable con acabado dorado.',details:'Cadena de 42 cm con extensión de 5 cm.',care:'Evitar perfumes y productos abrasivos. Guardar por separado.',featured:true,isNew:false},
    {slug:'blusa-amelie',name:'Blusa Amélie',categoryId:'cat-ropa',price:139900,compareAtPrice:null,image:'/images/blouse.jpg',color:'Blanco',hex:'#FAF8F3',sizes:['XS','S','M','L'],description:'Ligera, versátil y naturalmente sofisticada. Nuestra blusa de corte relajado es ese esencial al que siempre vuelves.',materials:'100% algodón.',details:'Corte relajado, manga larga y botones al frente.',care:'Lavar con colores similares. Planchar a temperatura media.',featured:false,isNew:true},
    {slug:'gafas-celine',name:'Gafas Céline',categoryId:'cat-accesorios',price:99900,compareAtPrice:129900,image:'/images/sunglasses.jpg',color:'Carey',hex:'#614536',sizes:['Única'],description:'Un toque de carácter para tus días de sol. Una montura atemporal con líneas suaves que completa cualquier conjunto.',materials:'Montura de acetato y lentes de policarbonato.',details:'Incluye estuche y paño de limpieza.',care:'Limpiar únicamente con paño de microfibra.',featured:false,isNew:true},
    {slug:'aretes-lumiere',name:'Aretes Lumière',categoryId:'cat-joyeria',price:69900,compareAtPrice:null,image:'/images/jewelry.jpg',color:'Dorado',hex:'#C5A16B',sizes:['Única'],description:'Pequeños detalles, grandes momentos. Aretes de acabado luminoso que aportan calidez a tu estilo diario.',materials:'Acero inoxidable con acabado dorado.',details:'Cierre de presión. Diseño liviano.',care:'Evitar contacto con cremas y perfumes.',featured:false,isNew:false},
    {slug:'bolso-mini-elan',name:'Bolso Mini Élan',categoryId:'cat-bolsos',price:159900,compareAtPrice:null,image:'/images/bag.jpg',color:'Cacao',hex:'#5D4336',sizes:['Única'],description:'Todo lo que necesitas, en su versión más especial. Un formato compacto que te acompaña del día a la noche.',materials:'Material sintético y forro textil.',details:'Asa corta y correa extraíble. Cierre magnético.',care:'Guardar en una bolsa de tela. Evitar superficies húmedas.',featured:false,isNew:true},
  ];
  for(const [index,p] of products.entries()){const {image,color,hex,sizes,...data}=p;await db.product.upsert({where:{slug:p.slug},update:{},create:{...data,images:{create:[{url:image,alt:`${p.name} — fotografía de referencia`,position:0}]},variants:{create:sizes.map((size,i)=>({sku:`LW-${String(index+1).padStart(3,'0')}-${i+1}`,size,color,colorHex:hex,stock:index===6?3:12+i}))}}});}
  await db.shopConfig.upsert({where:{id:'main'},create:{id:'main',value:{...defaultSettings,demoMode:true}},update:{value:{...defaultSettings,demoMode:true}}});
  if(process.env.SEED_ADMIN_EMAIL&&process.env.SEED_ADMIN_PASSWORD){await db.user.upsert({where:{email:process.env.SEED_ADMIN_EMAIL.toLowerCase()},create:{email:process.env.SEED_ADMIN_EMAIL.toLowerCase(),name:'Administración LUXE WOMAN',role:'ADMIN',passwordHash:await hash(process.env.SEED_ADMIN_PASSWORD,12)},update:{}});}
  console.log('Seed completado: 5 categorías y 8 productos ficticios. Modo demostración activo.');
}
main().catch(error=>{console.error(error instanceof Error?error.message:'Falló el seed');process.exitCode=1;}).finally(()=>db.$disconnect());
