'use client';
import Link from 'next/link';
import Image from 'next/image';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Heart, Menu, Minus, Plus, Search, ShoppingBag, Trash2, UserRound, X } from 'lucide-react';
import { brand, money } from '@/lib/config';
import { api } from '@/lib/api';
import { useStore } from './store';
const categories = ['Ropa', 'Zapatos', 'Joyería', 'Bolsos', 'Accesorios'];
const slugs = ['ropa', 'zapatos', 'joyeria', 'bolsos', 'accesorios'];
export function Header() {
  const store = useStore(); const pathname = usePathname(); const router = useRouter();
  const [menu, setMenu] = useState(false); const [search, setSearch] = useState(false); const [query, setQuery] = useState('');
  const total = store.cart?.items.reduce((sum, item) => sum + item.quantity, 0) || 0;
  return <><div className="announcement"><span>PIEZAS ESPECIALES. MUY TÚ.</span><span>Envíos a toda Colombia <span className="announcement-dot">·</span> Descubre tu próxima favorita <ArrowRight size={12} /></span><span>HECHO PARA INSPIRARTE</span></div>
    <header className="site-header"><div className="header-main"><button className="icon-button mobile-menu" aria-label="Abrir menú" aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X size={21} /> : <Menu size={21} />}</button><Link href="/" className="wordmark" aria-label={`${brand.name}, inicio`}>{store.settings?.brandName || brand.name}<small>THE ART OF BEING YOU</small></Link><nav className="desktop-nav" aria-label="Principal"><Link href="/" className={pathname === '/' ? 'active' : ''}>Inicio</Link><Link href="/catalogo?nuevo=true">Novedades <span className="nav-dot" /></Link>{categories.map((name, i) => <Link key={name} href={`/catalogo?categoria=${slugs[i]}`}>{name}</Link>)}</nav><div className="header-actions"><button className="icon-button" aria-label="Buscar productos" aria-expanded={search} onClick={() => setSearch(!search)}><Search size={20} /></button><Link className="icon-button account-icon" aria-label="Mi cuenta" href="/cuenta"><UserRound size={20} /></Link><Link className="icon-button" aria-label="Mis favoritos" href="/favoritos"><Heart size={20} />{store.favorites.length > 0 && <span className="count-dot">{store.favorites.length}</span>}</Link><button className="icon-button" aria-label={`Abrir bolsa, ${total} productos`} onClick={() => store.setCartOpen(true)}><ShoppingBag size={20} /><span className="bag-number">{total}</span></button></div></div>
    {menu && <nav className="mobile-nav" aria-label="Categorías">{[['Inicio', '/'], ['Novedades', '/catalogo?nuevo=true'], ...categories.map((name, i) => [name, `/catalogo?categoria=${slugs[i]}`]), ['Mi cuenta', '/cuenta']].map(([name, href]) => <Link href={href} key={name} onClick={() => setMenu(false)}>{name}<ArrowRight size={16} /></Link>)}</nav>}
    {search && <form className="search-bar" onSubmit={event => { event.preventDefault(); router.push(`/catalogo?buscar=${encodeURIComponent(query)}`); setSearch(false); }}><Search size={20} /><input autoFocus aria-label="Buscar en la boutique" placeholder="Encuentra esa pieza especial…" value={query} onChange={e => setQuery(e.target.value)} /><button type="submit" className="text-link">Buscar <ArrowRight size={16} /></button><button type="button" className="icon-button" aria-label="Cerrar búsqueda" onClick={() => setSearch(false)}><X size={20} /></button></form>}</header><CartDrawer /></>;
}
export function CartDrawer() {
  const { cartOpen, setCartOpen, cart, refresh, notify } = useStore(); const dialog = useRef<HTMLDialogElement>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { if (cartOpen && !dialog.current?.open) dialog.current?.showModal(); if (!cartOpen && dialog.current?.open) dialog.current.close(); document.body.style.overflow = cartOpen ? 'hidden' : ''; return () => { document.body.style.overflow = ''; }; }, [cartOpen]);
  async function update(id: string, quantity: number) { setBusy(true); try { await api(`/cart/items/${id}`, { method: quantity === 0 ? 'DELETE' : 'PATCH', ...(quantity === 0 ? {} : { body: JSON.stringify({ quantity }) }) }); await refresh(); } catch (error) { notify(error instanceof Error ? error.message : 'No pudimos actualizar tu bolsa', 'error'); } finally { setBusy(false); } }
  return <dialog className="cart-drawer" ref={dialog} onCancel={() => setCartOpen(false)} onClick={event => { if (event.target === dialog.current) setCartOpen(false); }} aria-label="Tu bolsa"><div className="drawer-content"><div className="drawer-title"><div><span className="eyebrow">TUS NUEVOS IMPRESCINDIBLES</span><h2>Mi bolsa <span>({cart?.items.length || 0})</span></h2></div><button className="icon-button" onClick={() => setCartOpen(false)} aria-label="Cerrar bolsa"><X /></button></div>{!cart?.items.length ? <div className="empty-state"><ShoppingBag size={40} strokeWidth={1} /><h3>Tu próxima favorita te espera</h3><p>Descubre nuestra selección y dale un toque especial a tu día.</p><Link className="button" href="/catalogo" onClick={() => setCartOpen(false)}>Explorar la boutique <ArrowRight size={16} /></Link></div> : <><div className="shipping-progress"><p>{cart.subtotal >= cart.freeShippingThreshold ? 'Tu pedido tiene envío gratis' : `Te faltan ${money(cart.freeShippingThreshold - cart.subtotal)} para envío gratis`}</p><progress max={cart.freeShippingThreshold} value={cart.subtotal} /></div><div className="cart-items">{cart.items.map(item => <article className="cart-item" key={item.id}><Image src={item.variant.product.images[0]?.url || '/images/dress.jpg'} alt={item.variant.product.name} width={92} height={118} /><div><span className="eyebrow">{item.variant.product.category.name}</span><Link href={`/producto/${item.variant.product.slug}`} onClick={() => setCartOpen(false)}>{item.variant.product.name}</Link><small>{item.variant.color} · Talla {item.variant.size}</small><strong>{money(item.lineTotal)}</strong><div className="quantity"><button disabled={busy || item.quantity <= 1} aria-label="Reducir cantidad" onClick={() => update(item.id, item.quantity - 1)}><Minus size={13} /></button><span>{item.quantity}</span><button disabled={busy || item.quantity >= item.variant.stock} aria-label="Aumentar cantidad" onClick={() => update(item.id, item.quantity + 1)}><Plus size={13} /></button></div></div><button className="icon-button remove-item" disabled={busy} aria-label={`Eliminar ${item.variant.product.name}`} onClick={() => update(item.id, 0)}><Trash2 size={16} /></button></article>)}</div><div className="cart-summary"><div><span>Subtotal</span><span>{money(cart.subtotal)}</span></div><div><span>Envío</span><span>{cart.shipping ? money(cart.shipping) : 'Gratis'}</span></div><div className="cart-total"><span>Total</span><strong>{money(cart.total)}</strong></div><Link className="button full-width" href="/checkout" onClick={() => setCartOpen(false)}>Continuar con mi pedido <ArrowRight size={16} /></Link><p className="muted">Pago por transferencia · Nequi y Daviplata</p></div></>}</div></dialog>;
}
export function Footer() {
  const { settings } = useStore();
  const waNumber = settings?.contactPhone?.replace(/\D/g, '') || '';
  return <footer className="site-footer"><div className="footer-main"><div className="footer-brand"><Link href="/" className="wordmark">{settings?.brandName || brand.name}</Link><p>El lujo de sentirte tú.<br />Piezas especiales para cada versión de ti.</p><span className="footer-origin">DESDE COLOMBIA, CON AMOR.</span></div><div><h3>Explora</h3><Link href="/catalogo?nuevo=true">Novedades</Link><Link href="/catalogo?categoria=ropa">Ropa</Link><Link href="/catalogo?categoria=bolsos">Bolsos y accesorios</Link><Link href="/catalogo?categoria=joyeria">Joyería</Link></div><div><h3>Estamos para ti</h3><Link href="/ayuda#envios">Envíos y entregas</Link><Link href="/ayuda#cambios">Cambios y devoluciones</Link><Link href="/ayuda#tallas">Guía de tallas</Link><Link href="/cuenta">Sigue tu pedido</Link></div><div><h3>Conectemos</h3><Link href="/nosotros">Nuestro universo</Link>{settings?.contactEmail ? <a href={`mailto:${settings.contactEmail}`}>{settings.contactEmail}</a> : <Link href="/ayuda#contacto">Atención al cliente</Link>}{waNumber && <a href={`https://wa.me/57${waNumber}?text=${encodeURIComponent('Hola LUXE WOMAN, deseo información sobre sus prendas y colecciones.')}`} target="_blank" rel="noopener noreferrer">WhatsApp: {settings?.contactPhone}</a>}<Link href="/cuenta">Mi cuenta</Link><Link href="/favoritos">Mis favoritos</Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {settings?.brandName || brand.name}. Todos los derechos reservados.</span><div><Link href="/legal/privacidad">Privacidad</Link><Link href="/legal/terminos">Términos y condiciones</Link></div><span className="payment-wordmarks">nequi <span>·</span> DaviPlata</span></div>{settings?.demoMode && <p className="demo-note">Boutique en desarrollo · Catálogo ilustrativo · No realices transferencias reales.</p>}</footer>;
}
