import { Inject, Controller, Get, Post, Patch, Delete, Body, Param, Query, Req, UploadedFile, UseInterceptors, BadRequestException, NotFoundException, ConflictException } from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { ApiTags } from '@nestjs/swagger';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { Database } from './database';
import { AuthedRequest, requireStaff, publicUser } from './auth';
import { CatalogService, productInclude } from './catalog';
import { OrdersService, orderInclude } from './orders';
import { MailService } from './mail';
import { StorageService } from './storage';
import { assertOrderTransition, settingsSchema, parse } from './domain';
const imageUrl=z.string().max(1000).refine(s=>s.startsWith('/images/')||/^https?:\/\//.test(s),'Usa una imagen local /images/ o una URL HTTPS.');
const productSchema=z.object({name:z.string().trim().min(2).max(120),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(150),description:z.string().trim().min(10).max(5000),categoryId:z.string().min(1),price:z.number().int().min(1).max(100000000),compareAtPrice:z.number().int().positive().max(100000000).nullable().optional(),details:z.string().max(3000).default(''),materials:z.string().max(1000).default(''),care:z.string().max(1000).default(''),featured:z.boolean().default(false),isNew:z.boolean().default(false),active:z.boolean().default(true),images:z.array(z.object({url:imageUrl,alt:z.string().max(200).optional()})).min(1).max(10),variants:z.array(z.object({sku:z.string().trim().min(2).max(80),size:z.string().trim().min(1).max(30),color:z.string().trim().min(1).max(40),colorHex:z.string().regex(/^#[0-9a-fA-F]{6}$/).default('#D9BFA9'),stock:z.number().int().min(0).max(100000)})).min(1).max(100)}).refine(p=>new Set(p.variants.map(v=>v.sku)).size===p.variants.length,'Cada SKU debe ser único.').refine(p=>new Set(p.variants.map(v=>`${v.size}:${v.color}`)).size===p.variants.length,'No repitas talla y color.');
@ApiTags('Administración')
@Controller('admin')
export class AdminController{
  constructor(@Inject(Database) private readonly db:Database,@Inject(CatalogService) private readonly catalog:CatalogService,@Inject(OrdersService) private readonly orders:OrdersService,@Inject(MailService) private readonly mail:MailService,@Inject(StorageService) private readonly storage:StorageService){}
  @Post('upload')
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: 10 * 1024 * 1024, files: 1 } }))
  async uploadImage(@Req() req: AuthedRequest, @UploadedFile() file?: Express.Multer.File) {
    requireStaff(req);
    if (!file) throw new BadRequestException('Selecciona una imagen.');
    const allowed = ['image/jpeg', 'image/png', 'image/webp', 'image/avif'];
    if (!allowed.includes(file.mimetype)) throw new BadRequestException('Formato no permitido. Usa JPG, PNG, WEBP o AVIF.');
    const result = await this.storage.upload(file, 'products');
    return { url: result.url, provider: result.provider };
  }
  @Get('metrics') async metrics(@Req() req:AuthedRequest){requireStaff(req,true);const [revenue,orders,customers,products,pendingPayments,lowStock,recentOrders,paid]=await Promise.all([this.db.order.aggregate({where:{paymentStatus:'APPROVED',status:{not:'CANCELLED'}},_sum:{total:true}}),this.db.order.count(),this.db.user.count({where:{role:'CUSTOMER'}}),this.db.product.count({where:{active:true}}),this.db.order.count({where:{paymentStatus:'UNDER_REVIEW'}}),this.db.productVariant.count({where:{stock:{lt:5},product:{active:true}}}),this.db.order.findMany({take:8,orderBy:{createdAt:'desc'},include:orderInclude}),this.db.order.findMany({where:{paymentStatus:'APPROVED',status:{not:'CANCELLED'}},select:{createdAt:true,total:true}})]);const months=new Map<string,number>();for(const o of paid){const month=o.createdAt.toISOString().slice(0,7);months.set(month,(months.get(month)||0)+o.total);}return{revenue:revenue._sum.total||0,orders,customers,products,pendingPayments,lowStock,recentOrders,salesByMonth:[...months.entries()].sort().map(([month,total])=>({month,total}))};}

  @Get('products') products(@Req() req:AuthedRequest,@Query() query:Record<string,string>){requireStaff(req);return this.catalog.products({limit:'100',...query},true);}
  @Post('products') async createProduct(@Req() req:AuthedRequest,@Body() body:unknown){const actor=requireStaff(req);const v=parse(productSchema,body);const {images,variants,...data}=v;return this.db.$transaction(async tx=>{const product=await tx.product.create({data:{...data,images:{create:images.map((i,position)=>({...i,alt:i.alt||v.name,position}))},variants:{create:variants}},include:productInclude});await tx.auditLog.create({data:{actorId:actor.id,action:'PRODUCT_CREATED',entityId:product.id}});return product;});}
  @Patch('products/:id') async updateProduct(@Req() req:AuthedRequest,@Param('id') id:string,@Body() body:unknown){const actor=requireStaff(req);const v=parse(productSchema,body);const {images,variants,...data}=v;return this.db.$transaction(async tx=>{const current=await tx.product.findUnique({where:{id},include:{variants:true}});if(!current)throw new NotFoundException('Producto no encontrado.');await tx.product.update({where:{id},data});await tx.productImage.deleteMany({where:{productId:id}});await tx.productImage.createMany({data:images.map((i,position)=>({productId:id,...i,alt:i.alt||v.name,position}))});for(const variant of variants){const existing=current.variants.find(i=>i.sku===variant.sku);if(existing)await tx.productVariant.update({where:{id:existing.id},data:variant});else await tx.productVariant.create({data:{productId:id,...variant}});}const removed=current.variants.filter(i=>!variants.some(v=>v.sku===i.sku));if(removed.length)await tx.productVariant.updateMany({where:{id:{in:removed.map(v=>v.id)}},data:{stock:0}});await tx.auditLog.create({data:{actorId:actor.id,action:'PRODUCT_UPDATED',entityId:id,metadata:{previousPrice:current.price,newPrice:v.price}}});return tx.product.findUniqueOrThrow({where:{id},include:productInclude});});}
  @Delete('products/:id') async archiveProduct(@Req() req:AuthedRequest,@Param('id') id:string){const actor=requireStaff(req);await this.db.$transaction([this.db.product.update({where:{id},data:{active:false}}),this.db.auditLog.create({data:{actorId:actor.id,action:'PRODUCT_ARCHIVED',entityId:id}})]);return{ok:true};}
  @Get('orders') listOrders(@Req() req:AuthedRequest){requireStaff(req);return this.db.order.findMany({include:orderInclude,orderBy:{createdAt:'desc'},take:200});}
  @Get('orders/:id') getOrder(@Req() req:AuthedRequest,@Param('id') id:string){requireStaff(req);return this.orders.get(id);}
  @Patch('orders/:id') async updateOrder(@Req() req:AuthedRequest,@Param('id') id:string,@Body() body:unknown){
    const actor=requireStaff(req);const v=parse(z.object({status:z.enum(['PENDING_PAYMENT','CONFIRMED','PREPARING','SHIPPED','DELIVERED','CANCELLED']).optional(),carrier:z.enum(['Coordinadora','Interrapidísimo','Entrega propia']).optional(),trackingNumber:z.string().max(100).optional(),trackingUrl:z.string().url().startsWith('https://').max(500).optional().or(z.literal('')),note:z.string().max(1000).optional()}),body);
    const order=await this.db.$transaction(async tx=>{const current=await tx.order.findUnique({where:{id},include:{items:true,shipment:true}});if(!current)throw new NotFoundException('Pedido no encontrado.');if(v.status)assertOrderTransition(current.status,v.status,current.paymentStatus);if(v.status==='SHIPPED'&&!(v.carrier||current.shipment?.carrier))throw new BadRequestException('Indica la transportadora antes de despachar.');if(v.status==='CANCELLED'&&actor.role!=='ADMIN')throw new BadRequestException('La cancelación requiere un administrador.');if(v.status==='CANCELLED'&&current.status!=='CANCELLED'){for(const item of current.items)await tx.productVariant.update({where:{id:item.variantId},data:{stock:{increment:item.quantity}}});}await tx.order.update({where:{id},data:{status:v.status}});if(v.carrier||v.trackingNumber||v.status==='SHIPPED'||v.status==='DELIVERED'){const carrier=v.carrier||current.shipment?.carrier;if(!carrier)throw new BadRequestException('Indica la transportadora.');await tx.shipment.upsert({where:{orderId:id},create:{orderId:id,carrier,trackingNumber:v.trackingNumber,trackingUrl:v.trackingUrl||null,...(v.status==='SHIPPED'?{shippedAt:new Date()}:{}),...(v.status==='DELIVERED'?{deliveredAt:new Date()}:{})},update:{carrier,trackingNumber:v.trackingNumber,trackingUrl:v.trackingUrl||undefined,...(v.status==='SHIPPED'?{shippedAt:new Date()}:{}),...(v.status==='DELIVERED'?{deliveredAt:new Date()}:{})}});}await tx.orderEvent.create({data:{orderId:id,status:v.status||current.status,message:v.note||({PREPARING:'Estamos preparando tu pedido.',SHIPPED:'Tu pedido ha sido enviado.',DELIVERED:'Pedido entregado.',CANCELLED:'Pedido cancelado. Si realizaste el pago, contacta a la tienda para gestionar su devolución.'} as Record<string,string>)[v.status||'']||'Información del pedido actualizada.'}});await tx.auditLog.create({data:{actorId:actor.id,action:'ORDER_UPDATED',entityId:id,metadata:v}});return tx.order.findUniqueOrThrow({where:{id},include:orderInclude});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});void this.mail.notify(order.userId,`Actualización de ${order.number}`,order.events.at(-1)?.message||'Tu pedido ha sido actualizado.').catch(()=>undefined);return order;
  }
  @Post('orders/:id/payment') async reviewPayment(@Req() req:AuthedRequest,@Param('id') id:string,@Body() body:unknown){
    const actor=requireStaff(req,true);const v=parse(z.object({decision:z.enum(['APPROVED','REJECTED']),note:z.string().trim().max(1000).optional()}),body);if(v.decision==='REJECTED'&&!v.note)throw new BadRequestException('Indica el motivo del rechazo.');
    const order=await this.db.$transaction(async tx=>{const current=await tx.order.findUnique({where:{id},include:{proofs:{orderBy:{createdAt:'desc'}}}});if(!current)throw new NotFoundException('Pedido no encontrado.');if(current.paymentStatus!=='UNDER_REVIEW'||current.status==='CANCELLED'||!current.proofs[0])throw new ConflictException('Este pedido no tiene un comprobante pendiente de revisión.');const changed=await tx.order.updateMany({where:{id,paymentStatus:'UNDER_REVIEW',status:{not:'CANCELLED'}},data:{paymentStatus:v.decision,status:v.decision==='APPROVED'?'CONFIRMED':'PENDING_PAYMENT'}});if(changed.count!==1)throw new ConflictException('Este pago ya fue revisado.');await tx.paymentProof.update({where:{id:current.proofs[0].id},data:{status:v.decision,note:v.note,reviewedBy:actor.id}});await tx.orderEvent.create({data:{orderId:id,status:v.decision,message:v.decision==='APPROVED'?'Pago aprobado. Tu pedido está confirmado.':`Comprobante rechazado: ${v.note}`}});await tx.auditLog.create({data:{actorId:actor.id,action:`PAYMENT_${v.decision}`,entityId:id,metadata:{proofId:current.proofs[0].id,note:v.note||''}}});return tx.order.findUniqueOrThrow({where:{id},include:orderInclude});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});void this.mail.notify(order.userId,`Pago de ${order.number}`,order.events.at(-1)?.message||'Tu pago fue revisado.').catch(()=>undefined);return order;
  }
  @Get('customers') async customers(@Req() req:AuthedRequest){requireStaff(req,true);const users=await this.db.user.findMany({orderBy:{createdAt:'desc'},take:500,include:{_count:{select:{orders:true}}}});return users.map(u=>({...publicUser(u),createdAt:u.createdAt,_count:u._count}));}
  @Patch('customers/:id/role') async role(@Req() req:AuthedRequest,@Param('id') id:string,@Body() body:unknown){const actor=requireStaff(req,true);const v=parse(z.object({role:z.enum(['CUSTOMER','EMPLOYEE','ADMIN'])}),body);return this.db.$transaction(async tx=>{const user=await tx.user.findUnique({where:{id}});if(!user)throw new NotFoundException('Cuenta no encontrada.');if(user.role==='ADMIN'&&v.role!=='ADMIN'&&await tx.user.count({where:{role:'ADMIN',active:true}})<=1)throw new BadRequestException('Debe existir al menos un administrador activo.');const updated=await tx.user.update({where:{id},data:v});await tx.session.deleteMany({where:{userId:id}});await tx.auditLog.create({data:{actorId:actor.id,action:'ROLE_UPDATED',entityId:id,metadata:v}});return publicUser(updated);},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
  @Get('settings') settings(@Req() req:AuthedRequest){requireStaff(req,true);return this.catalog.settings();}
  @Patch('settings') async updateSettings(@Req() req:AuthedRequest,@Body() body:unknown){const actor=requireStaff(req,true);const current=await this.catalog.settings();const partial=parse(settingsSchema.partial(),body);const value=parse(settingsSchema,{...current,...partial});if(new Set(value.paymentMethods.map(p=>p.id)).size!==2)throw new BadRequestException('Configura Nequi y Daviplata una sola vez.');if(!value.demoMode&&value.paymentMethods.some(p=>p.enabled&&(!p.number||!p.holder)))throw new BadRequestException('Configura número y titular de los métodos activos antes de activar ventas reales.');await this.db.$transaction([this.db.shopConfig.upsert({where:{id:'main'},create:{id:'main',value},update:{value}}),this.db.auditLog.create({data:{actorId:actor.id,action:'SETTINGS_UPDATED',entityId:'main'}})]);return this.catalog.settings();}
  @Get('audit') audit(@Req() req:AuthedRequest){requireStaff(req,true);return this.db.auditLog.findMany({orderBy:{createdAt:'desc'},take:100});}
}
