import { BadRequestException } from '@nestjs/common';
import { z } from 'zod';
export const addressSchema=z.object({label:z.string().max(60).optional(),name:z.string().trim().min(2).max(120),phone:z.string().trim().min(7).max(25),line1:z.string().trim().min(5).max(200),line2:z.string().trim().max(120).optional(),city:z.string().trim().min(2).max(80),department:z.string().trim().min(2).max(80),postalCode:z.string().max(15).optional()});
export const paymentMethodSchema=z.enum(['NEQUI','DAVIPLATA']);
export const settingsSchema=z.object({brandName:z.string().trim().min(1).max(80),shippingFee:z.number().int().min(0).max(1000000),freeShippingThreshold:z.number().int().min(0).max(100000000),contactEmail:z.string().email(),contactPhone:z.string().trim().max(30).default('3001234567'),demoMode:z.boolean(),paymentMethods:z.array(z.object({id:paymentMethodSchema,name:z.string().max(30),enabled:z.boolean(),number:z.string().max(30),holder:z.string().max(120),instructions:z.string().max(1000)})).length(2)});
export type Settings=z.infer<typeof settingsSchema>;
export const defaultSettings:Settings={brandName:'LUXE WOMAN',shippingFee:15000,freeShippingThreshold:300000,contactEmail:'contacto@luxewoman.com.co',contactPhone:'3001234567',demoMode:true,paymentMethods:[{id:'NEQUI',name:'Nequi',enabled:true,number:'3001234567',holder:'Jennifer López - LUXE WOMAN',instructions:'Transfiere a Nequi al 300 123 4567 por el valor de tu orden y sube tu comprobante o envíalo por WhatsApp.'},{id:'DAVIPLATA',name:'Daviplata',enabled:true,number:'3001234567',holder:'Jennifer López - LUXE WOMAN',instructions:'Pasa plata a Daviplata al 300 123 4567 por el valor de tu orden y sube tu comprobante o envíalo por WhatsApp.'}]};
export function parse<T>(schema:z.ZodType<T>,input:unknown):T {const result=schema.safeParse(input);if(!result.success)throw new BadRequestException(result.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; '));return result.data;}
export function totals(items:{price:number;quantity:number}[],settings:Pick<Settings,'shippingFee'|'freeShippingThreshold'>){const subtotal=items.reduce((n,i)=>n+i.price*i.quantity,0);const shipping=subtotal===0||subtotal>=settings.freeShippingThreshold?0:settings.shippingFee;return{subtotal,shipping,total:subtotal+shipping,freeShippingThreshold:settings.freeShippingThreshold};}
export function assertOrderTransition(from:string,to:string,paymentStatus:string){const allowed:Record<string,string[]>={PENDING_PAYMENT:['CANCELLED'],CONFIRMED:['PREPARING','CANCELLED'],PREPARING:['SHIPPED','CANCELLED'],SHIPPED:['DELIVERED'],DELIVERED:[],CANCELLED:[]};if(from===to)return;if(!allowed[from]?.includes(to))throw new BadRequestException('El cambio de estado del pedido no es válido.');if(['PREPARING','SHIPPED','DELIVERED'].includes(to)&&paymentStatus!=='APPROVED')throw new BadRequestException('El pago debe estar aprobado antes de preparar o enviar el pedido.');}
export function validateProof(buffer:Buffer,mime:string){const png=buffer.length>=8&&buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));const jpg=buffer.length>=3&&buffer[0]===255&&buffer[1]===216&&buffer[2]===255;const pdf=buffer.subarray(0,5).toString()==='%PDF-';if(buffer.length>5*1024*1024||buffer.length<8||!((png&&mime==='image/png')||(jpg&&mime==='image/jpeg')||(pdf&&mime==='application/pdf')))throw new BadRequestException('Adjunta un archivo JPG, PNG o PDF válido de máximo 5 MB.');return mime==='image/png'?'.png':mime==='image/jpeg'?'.jpg':'.pdf';}
